### PR TITLE
Fix query shared state

### LINKED ISSUE #94: Chainable queries should not use global state
Right now, ContentfulModel accomplishes chainable queries by tracking the request parameters within a class variable on the model class being queried. This is not thread safe, and can lead to subtle but problematic bugs within client apps.

Instead, ContentfulModel should use a QueryBuilder pattern, like what ActiveRecord has with it's `Relation` class.

Simplest test case:
```ruby
MyModel.params(abc: 123)
puts MyModel.all.load.length
```

Expected result: Should output the length of the loaded entries. 
Actual result: Exception because `abc` is not a valid parameter to the Contentful API.

I've implemented this change on my fork in the `feature/safe-chainable-queries` branch. This breaks compatibility, and I've also changed `find_by` to be called `where` and implemented a new `find_by` in terms of `where` and `limit(1)` and adjusted all the tests to match. I can PR this but it will require a major version tick. While I'd love to see these changes in the mainline, I think instead a new minor version of the gem needs to be released as per #92 before merging in any incompatible changes.

See my branch at: https://github.com/rezonant/contentful_model/tree/feature/safe-chainable-queries

### PR DESCRIPTION
**Pull request by dlitvakb**
Fixes #94

### CODE REVIEW

File: lib/contentful_model/query.rb [hunk 1]
```diff
@@ -10,19 +10,131 @@ def <<(parameters)
...
+    def find(id)
+      self << {'sys.id' => id}
+      self.load.first
+    end
+
+    def find_by(find_query = {})
+      find_query.each do |field, value|
+        key = if field.to_s.include?('sys.') || field.to_s.include?('fields.')
+                field
+              else
```
Comment (loudmouth) [inline lib/contentful_model/query.rb]: does it make sense to add nice handling for `sys` properties as well so if a user does `find_by(id)` the query resolves to `sys.id=`?
